# Generated by Django 3.2 on 2023-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titles",
            name="year",
            field=models.IntegerField(verbose_name="Год выпуска"),
        ),
    ]
