# Generated by Django 3.2 on 2023-03-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_titles_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titles",
            name="genre",
        ),
        migrations.CreateModel(
            name="TitleGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.genres",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.titles",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="titles",
            name="genre",
            field=models.ManyToManyField(
                blank=True,
                help_text="Жанр произведения",
                null=True,
                through="reviews.TitleGenre",
                to="reviews.Genres",
                verbose_name="Жанр",
            ),
        ),
    ]
