# Generated by Django 3.2 on 2023-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_auto_20230331_1445"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titles",
            name="genre",
            field=models.ManyToManyField(
                blank=True,
                help_text="Жанр произведения",
                through="reviews.TitleGenre",
                to="reviews.Genres",
                verbose_name="Жанр",
            ),
        ),
    ]
