# Generated by Django 3.2 on 2023-03-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0004_alter_titles_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="titles",
            name="year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год выпуска"
            ),
        ),
    ]
